[package]
name = "downman"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.80.*"

[dependencies]
flutter_rust_bridge = "1.80.*"
downloader = "0.2.7"
