[package]
name = "downman"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.80.*"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = [
  "rustls-tls",
  "stream",
  "gzip",
] }
flutter_rust_bridge = "1.82.*"
# don't use openssl in reqwest
tokio = { version = "1", features = ["full"] }
